name: Build and Run Docker Container for .NET Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t dotnet-app .

    - name: remove Docker Container Locally existed
      run: |
        docker rm -f dotnet-container || true 
        
    - name: Run Docker Container Locally
      run: |
        docker run -d -p 5000:80 --name dotnet-container dotnet-app
